services:
  - type: web
    name: chat-app-frontend
    env: node
    rootDir: frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: NODE_ENV
        value: production 